apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: kubernetes-go-hpa
  namespace: kubernetes-namespace-dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    name: kubernetes-deployments
    kind: Deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 25
