apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kubernetes-pvc
  namespace: kubernetes-namespace-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
