apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubernetes-service-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubernetes-read
rules:
  - apiGroups: [""]
    resources:
      ["pods", "services", "replicationcontrollers", "persistentvolumeclaims"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["metrics.k8s.io"]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: server-read-bind
subjects:
  - kind: ServiceAccount
    name: kubernetes-service-account
    namespace: kubernetes-namespace-dev
roleRef:
  kind: ClusterRole
  name: kubernetes-read
  apiGroup: rbac.authorization.k8s.io
